### ISSUE TITLE
Scopelint fails on parsing named mapping types

### ISSUE THREAD

**Issue by roberts-ivanovs** [ScopeLift/scopelint#24]
Scopelint fails on parsing named mappings. [Language feature introduced in Solidity 0.8.18](https://github.com/ethereum/solidity/releases/tag/v0.8.18)

The following Solidity snippet crashes `scopelint check`:

```solidity
mapping(address asset => uint256 balance) private _balances;
```

```
thread 'main' panicked at 'Parsing failed: [Diagnostic { loc: File(0, 958, 963), level: Error, ty: ParserError, message: "unrecognised token 'asset', expected \"=>\"", notes: [] }]', /[redacted]/.cargo/registry/src/github.com-1ecc6299db9ec823/scopelint-0.0.15/src/check/mod.rs:68:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by roberts-ivanovs** [comment]
I see that this only exists on the latest 0.0.15 version (the one currently available from crates.io). The latest version available on Github main branch does not have this issue ([post solang-parser update](https://github.com/ScopeLift/scopelint/commit/169c09b0f5dda6198258ce65e0669bdd885c62ac)).

Could a new release on crates.io please be created?

**Comment by mds1** [comment]
Ah, yea main has the updated parser to handle the new solidity features. Just prepared the release, should be live once this action finishes

**Comment by mds1** [comment]
v0.0.16 is now published!
